### ISSUE TITLE
Missing test for "prerender"

### ISSUE THREAD

**Issue by siusin** [w3c/page-visibility#28]
For visibilityState:

> If doc was prerendered [RESOURCE-HINTS] and has not previously transitioned to "visible", return "prerender".

It'd be nice to have a test for "prerender".

**Comment by igrigorik** [comment]
The problem is that support for prerender is dependent on RH, which not all browser support and I would prefer not to create a strong coupling between them; 'prerender' is optional and only applies if the browser implements RH. As such, my recommendation would be to:

- note PV integration as a requirement in RH test suite
- clearly indicate in PV spec that `prerender` is conditional on RH/prerender support
  - alternatively, as Todd suggested, we can move `prerender` extension into RH spec

**Comment by igrigorik** [comment]
@toddreifsteck @plehegar are you comfortable with the above?
