### ISSUE TITLE
support waitUntil semantics in pagevisibility?

### ISSUE THREAD

**Issue by spanicker** [w3c/page-visibility#36]
[Lifecycle onfreeze callback](https://github.com/WICG/web-lifecycle#proposal-mvp) will support ExtendableEvent waitUntil semantics.
It has been suggested that pagevisibility(hidden) should also support waitUntil as it can also be the "last legit callback" (and for consistency).

\cc @philipwalton - could you elaborate on what you had in mind?

**Comment by philipwalton** [comment]
As @spanicker said said, we've been [recommending developers use visibilitychange](https://www.igvita.com/2015/11/20/dont-lose-user-and-app-state-use-page-visibility/) as the last reliable point to detect session end, i.e. after page visibility changes to hidden, there's no guarantees you'll have another chance to run script before the page is torn down.

The problem is there are two very different situations in which page visibility can change to hidden:

1. When the user switches tabs
2. When the user navigates away or closes the tab

In situation (1), script can run on the page after the tab enters the background state, but in situation (2) no more script can run.

The problem is this disincentives developers from storing app state in IndexedDB because there's no way to save the final session state in the case of (2) above. By contrast, it incentives them to use localStorage because that API is synchronous and will work in both (1) and (2).

**Current workarounds:**

If developers want to use async APIs to store app state they have two options:

1. Proactively save app state after every change (since you don't know when the user will close the page)
2. If you're using Service Worker you can postMessage your app state to your service worker and inside the service worker you can run `event.waitUntil()` to store your app state in IndexedDB after the user has closed the tab.

Option (1) above is not ideal as it can lead to lots of unnecessary write, and (2) is not ideal for any third-party code that can't assume the use of Service Worker.

**Proposal:**

It'd be great if we had a way to unlock the functionality of (2) without requiring service worker.

My proposal is you'd be able to call `event.waitUntil()` on `visibilitychange`, which would allow you to run a limited subset of features (probably the same subset we're using in [onfreeze](https://github.com/WICG/web-lifecycle#proposal-mvp)) and the browser could run that independently of tearing down the page or loading the next page.

**Comment by spanicker** [comment]
1. waitUntil will need it's own upper time limit - any thoughts on that?
- in addition a time limit on the main callback might also make sense.

2. Supporting waitUntil during navigation could be tricky - depending on the time limit imposed (above).
In particular for same-process navigation in chrome, the end-of-life callbacks (unload etc) run synchronously for current document and block committing the navigation.

**Comment by bzbarsky** [comment]
One fundamental issue here is that when users close a tab or navigate away the expectation is that they are _done_ with that page.  It needs to stop consuming resources.

That said, we do already have a "try to delay us going away until we save stuff" mechanism in beforeunload.... but even there the user can override.

How do non-web apps handle this situation?  Presumably by relying on manual "save" actions by the user?

**Comment by spanicker** [comment]
On non-web / Android native app the above cases do not map exactly:
- case 1: user switches tabs - on native this is like the user clicking on the task-switcher or home-screen
- case 2: user navigates away or closes the tab - on native this like the user clicking on the task-switcher and then swiping the app away.

The user can be prompted when they attempt to leave the active / foreground app i.e. clicking on the task-switcher or home-screen but not when they swipe away an app from task-switcher (which is in background at that point). 

I'm not sure about the app state storage API on native apps and if they rely on transactional storage  that is async and how it is updated on user exit. It's a good question how mobile native handles this. @inexorabletash may have thoughts here.

On the web - we have historically used beforeunload to check pending state and for instance, if app hasn't finished persisting app state then the user is shown a modal dialog.
However beforeunload doesn't work in the case of mobile web: it is not run when the user goes away i.e. clicks task-switcher or home-screen, and it cannot be run when the user swipes away the app.

As @philipwalton said - we have identified onvisibilitychange as the last reliable callback that will run in all the cases where the user goes away (both desktop and mobile web). Therefore the request to enhance that API to support this case of pending state.

@bzbarsky brings up a good point: 
instead of assuming that the work to persist app state (basically user's data) MUST be done (and hence waitUntil support) -- the decision for whether the work should be done could be surfaced to the user.
(similar to how a native app can prompt user when they try to exit that there is unfinished work)
Perhaps something like beforeunload (that is ideally [declarative](https://docs.google.com/document/d/1SXY2zGDgh7L73kX3bXfxCi15IV_Z7RnH9lRIZnuqf6g/edit#heading=h.gzvfgo8u4hj7)). 
Not sure how it could work for the mobile web case of task-switcher? 
Even for desktop -  there are downsides to showing a dialog (eg. known issues of [beforeunload abuse](https://docs.google.com/document/d/1SXY2zGDgh7L73kX3bXfxCi15IV_Z7RnH9lRIZnuqf6g/edit#heading=h.xae3s41t3pza)).

**Comment by philipwalton** [comment]
We decided not to pursue this in Page Lifecycle's `onfreeze` callback because we felt that the [`IDBTransaction.commit()`](https://github.com/w3c/IndexedDB/pull/242). I think the same reasoning can apply here, and this can be closed.
