### ISSUE TITLE
typo: "5.3 onvisiblitychange event handler"

### ISSUE THREAD

**Issue by autonome** [w3c/page-visibility#37]
It's present in the document and sidebar of https://www.w3.org/TR/page-visibility/#onvisiblitychange-event-handler

It's not present in this repo, that I could find.

**Comment by autonome** [comment]
cc @marcoscaceres

**Comment by marcoscaceres** [comment]
It might just be that the published document is out of date (because it's on /TR/). @autonome, take a look at the Editor's draft instead:

https://w3c.github.io/page-visibility/#onvisibilitychange-event-handler-attribute

The TR document will eventually be superseded by a W3C Recommendation. 

Just for completeness, the `onvisibilitychange` is defined as part of the extensions to the `Document` object: 

https://w3c.github.io/page-visibility/#extensions-to-the-document-interface

**Comment by siusin** [comment]
Thanks @autonome . The group planed to publish a new version of Level 2 under /TR when #34 gets fixed.

[Tests and implementations](https://wpt.fyi/page-visibility/onvisibilitychange.html) are using the correct text `onvisibilitychange`.

**Comment by yoavweiss** [comment]
Is there an open issue here? Should we fix L1's typo?

**Comment by yoavweiss** [comment]
Seems like we have no process to revise published TR documents, even for a typo. The typo is fixed in the current version. Closing.

**Comment by siusin** [comment]
Note： The TR version is in the status of [W3C Proposed Recommendation](https://www.w3.org/2018/Process-20180201/#rec-pr) and have been reviewed by the Advisory Committee, right now there is no shortcut to publish a new PR to include editorial changes. We'll fix the typo when the spec moves to REC.
