### ISSUE TITLE
Treating .hidden as "historical" seems unhelpful

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/page-visibility#63]
Given the `document.hidden` is supported everywhere, and I doubt there are any plans for engines to drop it, I think the spec should stop treating it as "historical".

**Comment by yoavweiss** [comment]
While there aren't any immediate plans to remove support, I think that we should be discouraging web developers from using it (similar to [NavigationTiming's `timing` interface](https://www.w3.org/TR/navigation-timing-2/#obsolete)).

In terms of usage, I agree that removal is not likely. It seems that even the prefixed versions of this are [highly used](https://www.chromestatus.com/metrics/feature/timeline/popularity/196) (that's an upper bound including [both webkitHidden and webkitVisibilityState](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/dom/document.idl;l=197?q=hidden&ss=chromium%2Fchromium%2Fsrc:third_party%2Fblink%2Frenderer%2Fcore%2Fdom%2F)).

**Comment by marcoscaceres** [comment]
I'm still understanding the why would would discourage it tho? The rationale for discouraging the usage seems completely arbitrary. The attribute is just reflecting another attribute in boolean form and doesn't seem harmful in any way?

**Comment by yoavweiss** [comment]
@npm raised a good point on the last call - this was deemed historical when we had 3 visibility states: "visible", "hidden" and "prerender". The latter was removed, so this boolean is not actively harmful, just redundant.

**Comment by npm1** [comment]
So what's the status here - do we think we should remove the wording stating that the boolean is deprecated?

**Comment by marcoscaceres** [comment]
I'd object to it being considered "deprecated": it's not at risk of being removed, and it's also not in any way harmful. The attribute is clear and concise (particularly when used with a ternary operator), and I hold we should leave it to developers to use it if they think it's more clear. Given that we don't have a third-state (https://github.com/w3c/page-visibility/issues/63#issuecomment-671299957), the use of the enum value is more of a matter of stylistic programming opinion than anything else.

**Comment by jakub-g** [comment]
Hello, I just spent half a day on the subject today, so let me share a note from my side:

Even if `prerender` was removed from spec, it still lives in latest Safari.
(BTW was it implemented and then removed from Firefox and Chrome? if so, in which versions was it removed?)

On desktop Safari, each version from 7 through 14 (tested on BrowserStack), the initial `visibilityState` is `prerender` *(even if the page is visible to the user!)* in the following scenario:

0. Copy some URL to clipboard
1. Open new tab
2. Paste URL to the URL bar
3. Navigate to the URL (press enter)

You can test this under the following test page: https://jg-testpage.netlify.app/document.hidden/
![image](https://user-images.githubusercontent.com/1437027/98733962-a0d5b900-23a1-11eb-84c8-aabc8a0601b1.png)

_So IMO it makes sense to discourage people from using `document.hidden` because behavior in Safari is not great, to put it mildly -- it pretends to be hidden while it's not._

I edited [MDN entry](https://developer.mozilla.org/en-US/docs/Web/API/Document/hidden) and added the "historical" note and link to PV Level 2 spec before checking github, but now I came across this ticket, in which you removed it :)

Should the change from #64 be reverted? WDYT?

**Comment by cdumez** [comment]
We can drop "prerender" state in WebKit. I am not opposed to that, I simply wasn't aware this had been dropped from the specification. Note though that document.visibilityState will return "hidden", not "visible" in the cases where we were returning "prerender". When you type the URL in the URL bar, Safari preload in in a background view before you hit ENTER so initially, the document is loaded and running script but hidden.

Will fix issue in WebKit via https://bugs.webkit.org/show_bug.cgi?id=215851.

**Comment by yoavweiss** [comment]
Apologies, but it seems like it was premature to remove prerender from the specification (the [assumption](https://github.com/w3c/page-visibility/issues/42) was that it's not implemented by any browser).

Given Chrome's recent interest in [improved prerendering support](https://docs.google.com/document/d/1inejuvPONXPOLKTCcUzOBhPh6QOckMcltnR-E3xyZVQ/edit?ts=5f809f01#heading=h.nh9xf4k3tm9p) it might be worthwhile to revisit.

**Comment by npm1** [comment]
The change in https://github.com/w3c/page-visibility/pull/64 is not what removed prerender, it was https://github.com/w3c/page-visibility/pull/43.

> Apologies, but it seems like it was premature to remove prerender from the specification (the [assumption](https://github.com/w3c/page-visibility/issues/42) was that it's not implemented by any browser).
> 
> Given Chrome's recent interest in [improved prerendering support](https://docs.google.com/document/d/1inejuvPONXPOLKTCcUzOBhPh6QOckMcltnR-E3xyZVQ/edit?ts=5f809f01#heading=h.nh9xf4k3tm9p) it might be worthwhile to revisit.

Yea but at that session we also decided we need to look at all possible states to figure out the best way to expose them. Do we just go back to the three states, or do we wait until someone has gone through all the possibilities?

**Comment by yoavweiss** [comment]
By "revisit" I meant we need to look into the different options, not necessarily revert to the three states.

**Comment by cdumez** [comment]
I dropped "prerender" support from WebKit yesterday. If you are going to bring it back from the dead, please let us know ASAP.

**Comment by yoavweiss** [comment]
We [plan to discuss](https://docs.google.com/document/d/10dz_7QM5XCNsGeI63R864lF9gFqlqQD37B4q8Q46LMM/edit?pli=1#heading=h.x5ypwiimehi2) this on the next WG call. I believe that the current plan is not to revive the `prerender` visibility state.
