### ISSUE TITLE
Republish spec

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/page-visibility#65]
hi @plehegar and @yoavweiss, could we get this republished on TR please. Really need to exported definitions for a bunch of other specs 🙏😇

**Comment by yoavweiss** [comment]
@plehegar - friendly ping! :)

**Comment by mmocny** [comment]
I think this is probably blocked on the open L2 issues #48 and #51.  I'll see if I cannot resolve those.

**Comment by mmocny** [comment]
Update from discussion: #48 is resolved, and #51 need not be L2 blocking since it is spec-health related and not affecting functionality/testing/implementation, plus the same wording already existings in L1 which is already published.

We want to branch L2 so work on L3 can move ahead.  Before publishing L2 we will diff with L3 to see if there are changes that need backporting.

**Comment by yoavweiss** [comment]
@mmocny - I don't think we should block on those for simple publishing.

@plehegar - friendly ping! :)

/cc @caribouW3

**Comment by marcoscaceres** [comment]
Be great to get this republished, as it's now blocking republishing the updated Geolocation spec (can't link to "visible" and "hidden").

**Comment by marcoscaceres** [comment]
Filed https://github.com/w3c/transitions/issues/332 to transition the spec to a CR Snapshot.

**Comment by marcoscaceres** [comment]
Filed https://github.com/w3c/transitions/issues/332 to transition Page Visibility.

**Comment by marcoscaceres** [comment]
And we are up! :D 
https://www.w3.org/TR/2021/CR-page-visibility-2-20210518/
